test_features = [
    'Temperature',
    'Temperature_lag_1min',
    'Temperature_rolling_change_mean_15min',
    'Temperature_rolling_change_mean_10min',
    'Temperature_lag_10min',
    'Light',
    'CO2',
    'HumidityRatio',
    'Humidity_rolling_change_mean_15min',
    'Humidity_rolling_mean_15min',
    'Light_rolling_mean_10min',
    'Light_rolling_mean_5min',
    'Light_lag_1min',
    'Light_lag_5min',
    'Light_rolling_change_mean_10min',
    'CO2_rolling_std_15min',
    'CO2_rolling_std_10min',
    'CO2_rolling_change_mean_15min',
    'CO2_lag_1min',
    'CO2_rolling_change_std_10min',
]

test_features_2 = [
    'Light',
    'Light_lag_1min',
    'Light_lag_5min',
    'Light_change',
    'Light_rolling_mean_10min',
    'Light_rolling_mean_5min',
    'Light_rolling_change_mean_15min',
    'Light_rolling_change_mean_10min',
    'Light_rolling_change_mean_5min',
    'Light_roc_5min',
    'CO2',
    'CO2_rolling_std_15min',
    'CO2_rolling_std_10min',
    'CO2_rolling_change_mean_15min',
    'CO2_lag_1min',
    'CO2_rolling_change_std_10min',
    'Temperature',
    'Temperature_lag_1min',
    'Temperature_rolling_change_mean_15min',
    'Temperature_rolling_change_mean_10min',
    'Temperature_lag_10min',
    'Temperature_roc_5min',
]

less_features = [
    'Light',
    'Light_lag_1min',
    'Light_rolling_mean_5min',
    'Light_lag_5min',
    'Light_rolling_mean_10min',
    'Light_rolling_change_mean_10min',
    'Light_rolling_change_mean_15min',
    'Light_change',
    'Light_rolling_change_mean_5min',
    'Light_rolling_std_5min',
    'HumidityRatio_lag_10min',
    'Temperature',
    'Light_rolling_std_15min',
    'Temperature_lag_1min',
    'Temperature_rolling_mean_5min',
    'HumidityRatio_rolling_change_std_15min'
]

many_features = [
    'Light_lag_1min',
    'Light',
    'Light_change',
    'Light_lag_5min',
    'HumidityRatio_lag_1min',
    'Light_rolling_change_mean_5min',
    'Humidity_lag_10min',
    'Temperature_rolling_mean_5min',
    'HumidityRatio_lag_5min',
    'Temperature_rolling_mean_15min',
    'Humidity_rolling_mean_10min',
    'Temperature_rolling_mean_10min',
    'Light_rolling_std_10min',
    'Humidity',
    'Light_rolling_change_std_5min',
    'HumidityRatio_rolling_mean_5min',
    'Light_rolling_change_std_15min',
    'Light_rolling_std_15min',
    'HumidityRatio',
    'Humidity_rolling_std_10min',
    'Humidity_rolling_change_mean_5min',
    'Humidity_rolling_mean_15min',
    'HumidityRatio_rolling_std_10min',
    'Temperature_lag_10min',
    'Humidity_lag_1min',
    'Humidity_rolling_std_15min',
    'Temperature',
    'Temperature_rolling_change_std_15min',
    'Light_rolling_change_mean_10min',
    'Humidity_rolling_change_mean_15min',
    'Temperature_rolling_change_std_10min',
    'Light_rolling_std_5min',
    'HumidityRatio_lag_10min',
    'Humidity_rolling_change_mean_10min',
    'Humidity_lag_5min',
    'Humidity_rolling_change_std_5min',
    'Temperature_lag_1min',
    'Humidity_rolling_mean_5min',
    'Humidity_rolling_change_std_15min',
    'HumidityRatio_change',
    'CO2',
    'HumidityRatio_rolling_change_std_15min',
    'HumidityRatio_rolling_change_std_10min',
    'CO2_rolling_change_mean_15min',
    'Light_rolling_change_mean_15min',
    'Humidity_rolling_change_std_10min',
    'HumidityRatio_rolling_std_15min',
    'CO2_rolling_change_mean_5min',
    'Light_rolling_mean_5min',
    'Light_rolling_mean_10min',
    'Temperature_rolling_change_mean_15min',
    'CO2_rolling_std_15min',
    'CO2_rolling_change_std_15min',
    'Temperature_rolling_std_10min',
    'Humidity_rolling_std_5min',
    'HumidityRatio_pct_change',
    'CO2_lag_1min',
    'Temperature_rolling_change_std_5min',
    'Light_rolling_change_std_10min',
    'Temperature_rolling_std_15min',
    'CO2_rolling_change_std_10min',
    'HumidityRatio_rolling_mean_15min',
    'Light_lag_10min',
]

selector_option_1 = ['Temperature', 'Humidity', 'Light', 'CO2', 'HumidityRatio',
                     'Temperature_rolling_std_15min',
                     'Temperature_rolling_change_mean_15min',
                     'Temperature_roc_5min',

                     'Humidity_rolling_std_15min',
                     'Humidity_rolling_change_mean_15min',
                     'Humidity_roc_5min',

                     'Light_rolling_std_15min',
                     'Light_rolling_change_mean_15min',
                     'Light_roc_5min',

                     'CO2_rolling_std_15min',
                     'CO2_rolling_change_mean_15min',
                     'CO2_roc_5min',

                     'HumidityRatio_rolling_std_15min',
                     'HumidityRatio_rolling_change_mean_15min',
                     'HumidityRatio_roc_5min']

selector_option_2 = ['Light', 'CO2', 'HumidityRatio',
                     'Temperature_rolling_change_mean_15min',
                     'Temperature_roc_5min',

                     'Humidity_rolling_std_15min',
                     'Humidity_rolling_change_mean_15min',
                     'Humidity_roc_5min',

                     'CO2_rolling_change_mean_15min',

                     'HumidityRatio_rolling_std_15min',
                     'HumidityRatio_rolling_change_mean_15min',
                     'HumidityRatio_roc_5min']

selector_option_3 = ['Light', 'CO2', 'HumidityRatio',
                     'CO2_rolling_change_mean_15min',
                     'HumidityRatio_rolling_std_15min',
                     'HumidityRatio_rolling_change_mean_15min',
                     'HumidityRatio_roc_5min']

selector_option_4 = ['Temperature', 'Light', 'CO2', 'HumidityRatio',
                     'Temperature_rolling_std_15min',
                     'Temperature_rolling_change_mean_15min',
                     'Temperature_roc_5min',

                     'CO2_rolling_std_15min',
                     'CO2_rolling_change_mean_15min',
                     'CO2_roc_5min',

                     'HumidityRatio_rolling_std_15min',
                     'HumidityRatio_rolling_change_mean_15min',
                     'HumidityRatio_roc_5min']

promising_features = [
    'Temperature_rolling_change_mean_15min',
    'Temperature_rolling_change_mean_10min',
    'Temperature_roc_5min',
    'Temperature_rolling_change_mean_5min',
    'Temperature_rolling_change_std_15min',
    'Humidity_rolling_std_15min',
    'Humidity_rolling_change_std_15min',
    'Humidity_rolling_change_mean_15min',
    'Light_rolling_mean_5min',
    'Light',
    'Light_rolling_mean_15min',
    'Light_lag_1min',
    'CO2_rolling_std_15min',
    'CO2_rolling_change_std_15min',
    'CO2_rolling_change_std_10min',
    'CO2_rolling_change_mean_15min',
    'HumidityRatio_rolling_std_15min',
    'HumidityRatio_rolling_change_std_15min',
    'HumidityRatio_rolling_change_mean_15min',
]

temperature_features = [
 'Temperature',
 'Temperature_lag_1min',
 'Temperature_lag_5min',
 'Temperature_lag_10min',
 'Temperature_change',
 'Temperature_rolling_mean_15min',
 'Temperature_rolling_mean_10min',
 'Temperature_rolling_mean_5min',
 'Temperature_rolling_std_15min',
 'Temperature_rolling_std_10min',
 'Temperature_rolling_std_5min',
 'Temperature_rolling_change_mean_15min',
 'Temperature_rolling_change_mean_10min',
 'Temperature_rolling_change_mean_5min',
 'Temperature_rolling_change_std_15min',
 'Temperature_rolling_change_std_10min',
 'Temperature_rolling_change_std_5min',
 'Temperature_pct_change',
 'Temperature_roc_5min']

humidity_features = [
 'Humidity',
 'Humidity_lag_1min',
 'Humidity_lag_5min',
 'Humidity_lag_10min',
 'Humidity_change',
 'Humidity_rolling_mean_15min',
 'Humidity_rolling_mean_10min',
 'Humidity_rolling_mean_5min',
 'Humidity_rolling_std_15min',
 'Humidity_rolling_std_10min',
 'Humidity_rolling_std_5min',
 'Humidity_rolling_change_mean_15min',
 'Humidity_rolling_change_mean_10min',
 'Humidity_rolling_change_mean_5min',
 'Humidity_rolling_change_std_15min',
 'Humidity_rolling_change_std_10min',
 'Humidity_rolling_change_std_5min',
 'Humidity_pct_change',
 'Humidity_roc_5min']

light_features = [
 'Light',
 'Light_lag_1min',
 'Light_lag_5min',
 'Light_lag_10min',
 'Light_change',
 'Light_rolling_mean_15min',
 'Light_rolling_mean_10min',
 'Light_rolling_mean_5min',
 'Light_rolling_std_15min',
 'Light_rolling_std_10min',
 'Light_rolling_std_5min',
 'Light_rolling_change_mean_15min',
 'Light_rolling_change_mean_10min',
 'Light_rolling_change_mean_5min',
 'Light_rolling_change_std_15min',
 'Light_rolling_change_std_10min',
 'Light_rolling_change_std_5min',
 'Light_roc_5min']

co2_features = [
 'CO2',
 'CO2_lag_1min',
 'CO2_lag_5min',
 'CO2_lag_10min',
 'CO2_change',
 'CO2_rolling_mean_15min',
 'CO2_rolling_mean_10min',
 'CO2_rolling_mean_5min',
 'CO2_rolling_std_15min',
 'CO2_rolling_std_10min',
 'CO2_rolling_std_5min',
 'CO2_rolling_change_mean_15min',
 'CO2_rolling_change_mean_10min',
 'CO2_rolling_change_mean_5min',
 'CO2_rolling_change_std_15min',
 'CO2_rolling_change_std_10min',
 'CO2_rolling_change_std_5min',
 'CO2_pct_change',
 'CO2_roc_5min']

humidity_ratio_features = [
 'HumidityRatio',
 'HumidityRatio_lag_1min',
 'HumidityRatio_lag_5min',
 'HumidityRatio_lag_10min',
 'HumidityRatio_change',
 'HumidityRatio_rolling_mean_15min',
 'HumidityRatio_rolling_mean_10min',
 'HumidityRatio_rolling_mean_5min',
 'HumidityRatio_rolling_std_15min',
 'HumidityRatio_rolling_std_10min',
 'HumidityRatio_rolling_std_5min',
 'HumidityRatio_rolling_change_mean_15min',
 'HumidityRatio_rolling_change_mean_10min',
 'HumidityRatio_rolling_change_mean_5min',
 'HumidityRatio_rolling_change_std_15min',
 'HumidityRatio_rolling_change_std_10min',
 'HumidityRatio_rolling_change_std_5min',
 'HumidityRatio_pct_change',
 'HumidityRatio_roc_5min']

lag_features = ['Temperature',
                 'Humidity',
                 'Light',
                 'CO2',
                 'HumidityRatio',
                 'Temperature_lag_1min',
                 'Temperature_lag_5min',
                 'Temperature_lag_10min',
                 'Humidity_lag_1min',
                 'Humidity_lag_5min',
                 'Humidity_lag_10min',
                 'Light_lag_1min',
                 'Light_lag_5min',
                 'Light_lag_10min',
                 'CO2_lag_1min',
                 'CO2_lag_5min',
                 'CO2_lag_10min',
                 'HumidityRatio_lag_1min',
                 'HumidityRatio_lag_5min',
                 'HumidityRatio_lag_10min']

change_features = ['Temperature',
                     'Humidity',
                     'Light',
                     'CO2',
                     'HumidityRatio',
                     'Temperature_change',
                     'Temperature_rolling_change_mean_15min',
                     'Temperature_rolling_change_mean_10min',
                     'Temperature_rolling_change_mean_5min',
                     'Temperature_rolling_change_std_15min',
                     'Temperature_rolling_change_std_10min',
                     'Temperature_rolling_change_std_5min',
                     'Temperature_pct_change',
                     'Temperature_roc_5min',
                     'Humidity_rolling_change_mean_15min',
                     'Humidity_rolling_change_mean_10min',
                     'Humidity_rolling_change_mean_5min',
                     'Humidity_rolling_change_std_15min',
                     'Humidity_rolling_change_std_10min',
                     'Humidity_rolling_change_std_5min',
                     'Humidity_pct_change',
                     'Humidity_roc_5min',
                     'Light_change',
                     'Light_rolling_change_mean_15min',
                     'Light_rolling_change_mean_10min',
                     'Light_rolling_change_mean_5min',
                     'Light_rolling_change_std_15min',
                     'Light_rolling_change_std_10min',
                     'Light_rolling_change_std_5min',
                     'Light_roc_5min',
                     'CO2_change',
                     'CO2_rolling_change_mean_15min',
                     'CO2_rolling_change_mean_10min',
                     'CO2_rolling_change_mean_5min',
                     'CO2_rolling_change_std_15min',
                     'CO2_rolling_change_std_10min',
                     'CO2_rolling_change_std_5min',
                     'CO2_pct_change',
                     'CO2_roc_5min',
                     'HumidityRatio_change',
                     'HumidityRatio_rolling_change_mean_15min',
                     'HumidityRatio_rolling_change_mean_10min',
                     'HumidityRatio_rolling_change_mean_5min',
                     'HumidityRatio_rolling_change_std_15min',
                     'HumidityRatio_rolling_change_std_10min',
                     'HumidityRatio_rolling_change_std_5min',
                     'HumidityRatio_pct_change',
                     'HumidityRatio_roc_5min']

rolling_features = ['Temperature',
                     'Humidity',
                     'Light',
                     'CO2',
                     'HumidityRatio',
                     'Temperature_rolling_mean_15min',
                     'Temperature_rolling_mean_10min',
                     'Temperature_rolling_mean_5min',
                     'Temperature_rolling_std_15min',
                     'Temperature_rolling_std_10min',
                     'Temperature_rolling_std_5min',
                     'Humidity_rolling_mean_15min',
                     'Humidity_rolling_mean_10min',
                     'Humidity_rolling_mean_5min',
                     'Humidity_rolling_std_15min',
                     'Humidity_rolling_std_10min',
                     'Humidity_rolling_std_5min',
                     'Light_rolling_mean_15min',
                     'Light_rolling_mean_10min',
                     'Light_rolling_mean_5min',
                     'Light_rolling_std_15min',
                     'Light_rolling_std_10min',
                     'Light_rolling_std_5min',
                     'CO2_rolling_mean_15min',
                     'CO2_rolling_mean_10min',
                     'CO2_rolling_mean_5min',
                     'CO2_rolling_std_15min',
                     'CO2_rolling_std_10min',
                     'CO2_rolling_std_5min',
                     'HumidityRatio_rolling_mean_15min',
                     'HumidityRatio_rolling_mean_10min',
                     'HumidityRatio_rolling_mean_5min',
                     'HumidityRatio_rolling_std_15min',
                     'HumidityRatio_rolling_std_10min',
                     'HumidityRatio_rolling_std_5min']

test_features_3 = light_features + [
    'CO2',
    'CO2_rolling_std_15min',
    'CO2_rolling_std_10min',
    'CO2_rolling_change_mean_15min',
    'CO2_lag_1min',
    'CO2_rolling_change_std_10min',
    'Temperature',
    'Temperature_lag_1min',
    'Temperature_rolling_change_mean_15min',
    'Temperature_rolling_change_mean_10min',
    'Temperature_lag_10min',
    'Temperature_roc_5min',
]